repos:
    - repo: https://github.com/PyCQA/isort
      rev: 6.0.1
      hooks:
          - id: isort
            args: [ "--settings-path=pyproject.toml" ]

    - repo: https://github.com/pre-commit/mirrors-yapf
      rev: v0.32.0
      hooks:
          - id: yapf
            args: [ "--style", "pyproject.toml", "-i" ]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.13.0
      hooks:
          - id: ruff
            args: [ "--config=pyproject.toml" ]
          - id: ruff-format
            args: [ "--config=pyproject.toml" ]

    - repo: https://github.com/PyCQA/docformatter
      rev: v1.7.7
      hooks:
          - id: docformatter
            args: [ "--config=pyproject.toml" ]

    - repo: https://github.com/codespell-project/codespell
      rev: v2.4.1
      hooks:
          - id: codespell
            args: [ "--config=pyproject.toml" ]
